### ISSUE TITLE
Splitting isn't working

### ISSUE THREAD

**Issue by Donneh** [pathartl/BananaSplit#17]
I've been trying to split my video file but nothing seems to happen. Finding the black frames and choosing where to split does work.

I don't see any errors in the console either.

Windows 10
ffmpeg version: N-78410-g588e2e3
PHP: 7.0.2
Video is an .mkv file.

EDIT: They instantly turn green/succesfull.

**Comment by touche112** [comment]
Same here.  I can't figure out what's going on...

**Comment by TokugawaHeavyIndustries** [comment]
@Donneh - Are you using IIS or another web server, like Apache portable?

**Comment by gldn** [comment]
I had this problem too.

I fixed it by adding ".mp4" to the end of the output name. If I didn't enter any file extension, the queue would instantly turn green.

**Comment by pathartl** [comment]
Closing this. I was dumb and should have never used PHP.
