### ISSUE TITLE
Thumbnails are NaN

### ISSUE THREAD

**Issue by gldn** [pathartl/BananaSplit#18]
Using dahlgren's docker (https://github.com/Dahlgren/docker-banana-split/), I can't see thumbnails.  After letting FFMPEG detect black screens, the thumbnails are broken images and the link shows the timecode as NaN.  For example, "http://server:port/video.php?function=thumbnail&time=NaN&f=filename.mp4"

If I manually replace NaN with a whole number (but NOT a number with a decimal place), I can manually generate images in a browser window without issue.

Notwithstanding the lack of thumbnails, splitting works fine.

**Comment by pathartl** [comment]
Sorry, never replied to this issue. The PHP-based version is old. The Electron version should work better.
