### ISSUE TITLE
I cannot navigate to any other harddrive. 

### ISSUE THREAD

**Issue by Hayatory** [pathartl/BananaSplit#19]
From what i have tried i cannot navigate to any other hard drive but D: which is default in the navigation.

**Comment by Safemode** [comment]
From what I've noticed with it, it depends on what drive you're running the program from. So if you move it to another drive, it should show the folders/files on there

**Comment by pathartl** [comment]
Closing this. Old version was crap and the newer Winforms version works with other drives.
