### ISSUE TITLE
Multiple Issues that I have encountered

### ISSUE THREAD

**Issue by KleinReveche** [pathartl/BananaSplit#22]
The Issues:
1. I tried Matroska Chapters processing method but it crashes the app. 
2. The About Window doesn't show up, so you need a bit of tweaking. 
3. I can't seem to process Multiple splits in one video, I am splitting my Videos to Opening Theme, 1st Episode, 2nd Episode. My current workaround is processing it twice which is time consuming because I have a Pentium Laptop.
4. The Settings Window errors out when you open it multiple times in an instance.
5. Progress Bar needs to actually show progress of scanning for black frames. (Although maybe it's not your fault, ffmpeg does not generally have progress bars to my knowledge, [Maybe this'll help.](https://github.com/sidneys/ffmpeg-progressbar-cli) for some reference)
6. Processing also is not responding properly when you click the button, sometimes it does, sometimes it doesn't.
7. A new Video track that is completely black is added. It's format is MJPEG.

Other:
1. It is compatible with Linux through WINE. I prefer using it on Linux because it is much more stable than on Windows 10 on my experience. (I have a slow laptop.) I don't know If it will be compatible with WINE in the future since it depends on the framework you are using.
2. Appreciate your work, maybe it's a free time kind of thing but I am saved by it from learning complicated stuff about ffmpeg and it's rather complicated ways.
3. This is a constructive Criticism and is not meant to be taken offense. I look forward for more.

**Comment by pathartl** [comment]
New build has been published: [v3.2.1](https://github.com/pathartl/BananaSplit/releases/tag/v3.2.1)

Everything but the about window should be covered in this build.
