### ISSUE TITLE
All files in queue

### ISSUE THREAD

**Issue by Arctic4161** [pathartl/BananaSplit#23]
Doesn't process all the files in the queue after selecting the split frame.

**Comment by ricardosabino** [comment]
Hi, I've noticed a similar problem (or maybe it's the same). So what happens is if you press the checkbox beside the image where you want to split then the program doesn't recognize that as a selected frame, you actually have to click on top of the image and not on the checkbox. I've been doing some updates to the program and I'll try to fix this one too when I find out what's causing it.

**Comment by Arctic4161** [comment]
@ricardosabino I have also recently upgraded to win 11 and the program doesn't work at all. I appreciate the information about the queue, if only it worked now lol

**Comment by ricardosabino** [comment]
Unfortunately I don't have a machine with windows 11 yet. I can't say for sure what it is but it might just need to be compiled there (less likely) or you might be missing an older .net framework installed (more likely). I'll update here once I get a chance to check it on windows 11.

**Comment by pathartl** [comment]
@Arctic4161 Confirmed not working on Windows 11. The app is built as self-contained so it shouldn't need any specific pre-installed .NET Framework version. I will have to debug this a bit and figure out what's exactly going on. It seems like the black frame detection is working fine, just processing the queue doesn't do anything.

**Comment by Arctic4161** [comment]
@pathartl @ricardosabino I am glad to know that you guys are working on this and that this project isn't dead. It is needed, I don't think there are any other options out there

**Comment by pathartl** [comment]
New build has been published: [v3.2.1](https://github.com/pathartl/BananaSplit/releases/tag/v3.2.1)
