### ISSUE TITLE
re encode to mp4

### ISSUE THREAD

**Issue by NinFanBoyFTW** [pathartl/BananaSplit#25]
Hi I just found your program and it has been great so far. I just wanted to know if there would be a way to change the default MKV output to MP4. I saw this was in the known limitations but if it would be possible to change this program would be perfect. Thanks again

**Comment by Arctic4161** [comment]
In settings if you put .mp4 behind "{destination}" you will output .mp4. It'll look weird because you'll see .mkv.mp4 but it'll be mp4. 

To reiterate it'll be "{destination}".mp4 under FFMPEG Arguments.
