### ISSUE TITLE
Clicking Process Queue does nothing

### ISSUE THREAD

**Issue by ManlyJack** [pathartl/BananaSplit#26]
I load up a file, select my black frames, hit process queue and it instantly says "Done Encoding!" and has done nothing at all.

**Comment by ManlyJack** [comment]
Reading another issue I see that you have to click on the Frame itself instead of the checkbox, doing so made the app work correctly.

**Comment by ricardosabino** [comment]
I just created a PR to fix this problem.. hopefully it will make it to the next build.

**Comment by pathartl** [comment]
New build has been published: [v3.2.1](https://github.com/pathartl/BananaSplit/releases/tag/v3.2.1)
